{
    "swagger": "2.0",
    "info": {
        "title": "RwPay API",
        "version": "0.0.0"
    },
    "basePath": "/api",
    "paths": {
        "/transaction_token": {
            "post": {
                "summary": "Get token for transaction",
                "operationId": "getTransactionToken",
                "parameters": [
                    {
                        "name": "commerce_transaction_number",
                        "in": "query",
                        "description": "reference number",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "amount",
                        "in": "query",
                        "description": "amount to be paid",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "payment_type",
                        "in": "query",
                        "description": "method of payment(momo,airtel,card) ",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "successful operation"
                    },
                    "406": {
                        "description": "not acceptable"
                    },
                    "500": {
                        "description": "internal server error"
                    }
                }
            }
        }
    },
    "definitions": {}
}